exclude: .*(migrations\/|\.devcontainer\/|\.vscode\/|\.gitignore).*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10
        args: ["--config=./pyproject.toml"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path=./pyproject.toml"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--config=./pyproject.toml"]
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
        args: ["--config=./pyproject.toml"]
  # - repo: local # TODO: the change from django test to pytest made this hook ( & testing in general ) a lot slower <- go back django test
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry:  pytest -n auto
  #       types: [python]
  #       pass_filenames: true
  #       language: system
