[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120

[flake8]
max-line-length=120

[tool.djlint]
profile="django"
ignore = "H031"
