# Generated by Django 5.0.6 on 2024-06-19 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("IN", "Incoming"), ("FI", "Finished"), ("CA", "Canceled")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(blank=True, related_name="attendees", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
                "indexes": [
                    models.Index(fields=["-date", "-time", "status"], name="events_even_date_15360d_idx"),
                    models.Index(fields=["created_by"], name="events_even_created_95418c_idx"),
                ],
            },
        ),
    ]
