# Generated by Django 5.0.6 on 2024-06-21 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, related_name="attended_events", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="created_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.event"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date", "status"], name="events_even_date_d112a8_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["owner"], name="events_even_owner_i_52e16c_idx"),
        ),
    ]
