# Generated by Django 5.0.6 on 2024-06-19 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, related_name="event_attendees", to=settings.AUTH_USER_MODEL),
        ),
    ]
