# Generated by Django 5.0.6 on 2024-06-19 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, related_name="event_attendees", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date", "-time", "status"], name="events_even_date_15360d_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_by"], name="events_even_created_95418c_idx"),
        ),
    ]
