# Generated by Django 5.0.6 on 2024-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("IN", "Incoming"), ("FI", "Finished"), ("CA", "Canceled")],
                max_length=2,
                null=True,
            ),
        ),
    ]
