# Generated by Django 5.0.6 on 2024-06-20 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_attendees_alter_event_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_created_95418c_idx",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="created_by",
            new_name="owner",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["owner"], name="events_even_owner_i_52e16c_idx"),
        ),
    ]
