# Generated by Django 5.0.6 on 2024-06-20 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_event_events_even_created_95418c_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_date_15360d_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date", "status"], name="events_even_date_d112a8_idx"),
        ),
    ]
